{
  lib,
  config,
  ...
}:
let
  cfg = config.user.desktop.programs.emulators.kitty;
in
{
  options.user.desktop.programs.emulators.kitty = {
    enable = lib.mkEnableOption "Enable Kitty";
  };
  config = lib.mkIf cfg.enable {
    programs.kitty = {
      enable = true;
      font = {
        size = 12;
        name = "JetBrains Mono";
      };

      # Colors are loaded at runtime from ~/.config/kitty/colors.conf
      # generated by matugen via qs-theme-reload. The file is not
      # managed by home-manager so matugen can overwrite it freely.
      extraConfig = "include ~/.config/kitty/colors.conf";

      settings = {
        scrollback_lines = 10000;
        window_padding_width = 15;
        placement_strategy = "center";

        allow_remote_control = "yes";
        listen_on = "unix:/tmp/kitty-matugen";
        enable_audio_bell = "no";
        visual_bell_duration = "0.1";

        copy_on_select = "clipboard";
      };
    };
  };
}
