# GENERATED BY nix-configurator
{
  device.build = "7d9b1ccfe7a6dcd63cecb225e3eb6ab37044ec6279ad1d5a529a36332ec7c479";
  device.core.disableDefaults = true;
  device.core.locale.defaultLocale = "en_US.UTF-8";
  device.core.locale.supportedLocales = [
    "en_US.UTF-8/UTF-8"
    "cs_CZ.UTF-8/UTF-8"
  ];
  device.core.locale.timeZone = "Europe/Prague";
  device.core.network.domain = "clients.joka00.dev";
  device.core.network.services.enableAvahi = true;
  device.core.network.services.enableNetworkManager = true;
  device.core.network.services.enableResolved = true;
  device.core.securityRules.enable = true;
  device.core.shells.fish.enable = true;
  device.core.shells.zsh.enable = false;
  device.desktop.gamemode.enable = true;
  device.desktop.wayland.desktopManager.gnome.enable = false;
  device.desktop.wayland.desktopManager.plasma6.enable = false;
  device.desktop.wayland.displayManager.gdm.enable = true;
  device.desktop.wayland.windowManager.hyprland.enable = true;
  device.desktop.wayland.windowManager.sway.enable = false;
  device.server.auth.freeipa.enable = false;
  device.server.auth.keycloak.enable = false;
  device.server.cache.enable = false;
  device.server.databases.mysql.enable = false;
  device.server.databases.postgresql.enable = false;
  device.server.git.daemon.enable = false;
  device.server.git.cgit.enable = false;
  device.server.hosting.website.enable = false;
  device.server.hydra.enable = false;
  device.server.minecraft.enable = false;
  device.server.nixConfigurator.enable = false;
  device.server.services.fail2ban.enable = false;
  device.server.services.headscale.enable = false;
  device.server.services.web.nginx.enable = false;
  device.server.services.web.acme.enable = false;
  device.server.teamspeak.enable = false;
  device.utils.kdeconnect.enable = true;
  device.utils.virtualisation.docker.enable = true;
  device.utils.virtualisation.libvirtd.enable = false;
  device.utils.virtualisation.podman.enable = true;
}
