# GENERATED BY nix-configurator
{
  device.build = "7fbd83526f387ab5b4acab76e64aa00a0b8bf066529129d150c2b42c9e31a197";
  device.core.disableDefaults = true;
  device.core.locale.defaultLocale = "en_US.UTF-8";
  device.core.locale.supportedLocales = [
    "en_US.UTF-8/UTF-8"
    "cs_CZ.UTF-8/UTF-8"
  ];
  device.core.locale.timeZone = "Europe/Prague";
  device.core.network.domain = "clients.joka00.dev";
  device.core.network.services.enableAvahi = true;
  device.core.network.services.enableNetworkManager = true;
  device.core.network.services.enableResolved = true;
  device.core.securityRules.enable = true;
  device.core.shells.fish.enable = true;
  device.core.shells.zsh.enable = false;
  device.desktop.gamemode.enable = true;
  device.desktop.wayland.displayManager.gdm.enable = true;
  device.desktop.wayland.windowManager.hyprland.enable = true;
  device.server.cache.enable = false;
  device.server.databases.mysql.enable = false;
  device.server.databases.postgresql.enable = true;
  device.server.hydra.enable = false;
  device.server.minecraft.enable = false;
  device.server.proxy.traefik.enable = true;
  device.server.services.fail2ban.enable = false;
  device.server.services.headscale.enable = false;
  device.server.services.hosting.website.enable = false;
  device.server.teamspeak.enable = false;
  device.utils.kdeconnect.enable = true;
  device.utils.virtualisation.docker.enable = false;
  device.utils.virtualisation.libvirtd.enable = true;
  device.utils.virtualisation.podman.enable = true;
}
